---
#- name: "Copy openrc to rally | Tempest task"
#  shell: |
#     docker cp "{{ testwaves_openrc }}" rally:/var/lib/rally/admin-openrc.sh
#
#     docker exec -i -u0 rally chown rally.rally /var/lib/rally/admin-openrc.sh

- name: "Copy task files | Rally task template"
  copy:
    src: files/tasks/
    dest: "{{ testwaves_directories.scenarios_dir }}"


- name: "Templating a tasks | Rally task template"
  template:
    src: templates/task_args.j2
    dest: "{{ testwaves_directories.scenarios_dir }}/task_args.yaml"
    owner: root
    group: root
    mode: 0644


- name: "Start rally test | Rally task"
  shell: |
    rally task start {{ testwaves_directories.scenarios_dir }}/task.yaml --task-args-file {{ testwaves_directories.scenarios_dir }}/task_args.yaml
  ignore_errors: yes

- name: "Report rally test | Rally task"
  shell: |
    rally task report  --out {{ testwaves_directories.reports_dir }}/rally_report{{ ansible_date_time.date }}.html


- name: "Send rally report to Nexus host | Rally task"
  shell: |
    curl -v -u {{ nexus_user }}:{{ nexus_pass }} --upload-file {{ testwaves_directories.reports_dir }}/rally_report{{ ansible_date_time.date }}.html {{ nexus_repo }}
